-- AlterTable
ALTER TABLE `access_rights` ADD COLUMN `can_create` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `can_delete` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `can_manage` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `can_update` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `can_view` TINYINT NOT NULL DEFAULT 0;
