-- CreateTable
CREATE TABLE `employees` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `qrcode` VARCHAR(20) NULL,
    `dept_id` INTEGER NOT NULL,
    `designation_id` INTEGER NOT NULL,
    `username` VARCHAR(50) NOT NULL,
    `password` VARCHAR(50) NOT NULL,
    `dept_section` VARCHAR(150) NULL,
    `fname` VARCHAR(50) NOT NULL,
    `mname` VARCHAR(50) NOT NULL,
    `lname` VARCHAR(50) NOT NULL,
    `ext_name` VARCHAR(50) NULL,
    `birth_date` DATE NULL,
    `birth_place` VARCHAR(100) NULL,
    `gender` VARCHAR(10) NULL,
    `civil_status` VARCHAR(30) NULL,
    `height` VARCHAR(10) NULL,
    `weight` VARCHAR(10) NULL,
    `blood_type` VARCHAR(5) NULL,
    `gsis_id` VARCHAR(30) NULL,
    `pagibig_id` VARCHAR(30) NULL,
    `phic_id` VARCHAR(30) NULL,
    `sss_id` VARCHAR(30) NULL,
    `tin_id` VARCHAR(30) NULL,
    `agency_id` VARCHAR(30) NULL,
    `pin` VARCHAR(30) NULL,
    `citizenship` VARCHAR(50) NULL,
    `citizenship_country` VARCHAR(30) NULL,
    `tel_no` VARCHAR(20) NULL,
    `mobile_no` VARCHAR(20) NULL,
    `email` VARCHAR(100) NULL,
    `spouse_fname` VARCHAR(50) NULL,
    `spouse_mname` VARCHAR(50) NULL,
    `spouse_lname` VARCHAR(50) NULL,
    `spouse_ename` VARCHAR(20) NULL,
    `spouse_occupation` VARCHAR(50) NULL,
    `spouse_employer` VARCHAR(150) NULL,
    `spouse_business_address` VARCHAR(150) NULL,
    `spouse_tel_no` VARCHAR(20) NULL,
    `father_fname` VARCHAR(50) NULL,
    `father_mname` VARCHAR(50) NULL,
    `father_lname` VARCHAR(50) NULL,
    `father_ename` VARCHAR(50) NULL,
    `mother_fname` VARCHAR(50) NULL,
    `mother_mname` VARCHAR(50) NULL,
    `mother_lname` VARCHAR(50) NULL,
    `date_hired` DATE NULL,
    `type` VARCHAR(50) NULL,
    `flexi_time` BOOLEAN NOT NULL DEFAULT false,
    `employment_status` CHAR(2) NOT NULL DEFAULT 'R',
    `status` BOOLEAN NOT NULL DEFAULT true,
    `prc_id` VARCHAR(50) NULL,
    `login_token` VARCHAR(150) NULL,

    UNIQUE INDEX `qrcode_UNIQUE`(`qrcode`),
    UNIQUE INDEX `username`(`username`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
